version: '3.2'

services:
  app:
    image: sapper-container:dev
    build:
      context: ./app
    environment:
      - TZ=JST-9
    volumes:
      - type: bind
        source: ../
        target: /home/workspace
    command: sh -c "yarn dev"
    networks:
      - sapper-container
    ports:
      - "3000:3000"


networks:
  sapper-container:
    external: false
